<?php include('top.php'); ?>
<script>
    //tooltip
    $(function() {
        $( "[data-toggle='tooltip']" ).tooltip();
    });
</script>
<!-- Begin page content -->
<div class="page-header">
	<p class="lead">Data Management Planning</p>
</div>
<div data-spy="scroll" class="container" data-target="dmp">
      <div class="row">
        <div class="col-12 col-md-12 col-lg-12">
        <div class="col-6 col-md-6 col-lg-6">
          <div style="margin-left:-15px;" class="dmp_ex">
            <h2>We can help:</h2>
            <hr>
            <ul>
            	<li>Formulate and write data management plans for grant proposals</li>
            	<li>Identify appropriate repositories/archives for your research data</li>
            	<li>Provide training or information about data management planning to faculty members</li>
            </ul>
          </div>
        </div>

        <div class="col-2 col-md-2 col-lg-2">
        </div>

        <div class="col-4 col-md-4 col-lg-4">
          <div style="width:100%;" class="dmp_ex image">
            <h2>DMPTool</h2>
            <hr>
            <a href="https://dmptool.org/user_sessions/institution"><img src="images/DMPTlogo.png" /></a>
          </div>
        </div>
    </div>
    </div> <!-- /row -->

<br />
<br />

    <div class="row">
    	<div class="col-12 col-md-12 col-lg-12">
          <div class="service">
            <h2>Funding agency data policies</h2>
            <hr>
            <row class="row">
            <h2>National Institutes of Health</h2>
	            <p>NIH endorses the timely release and sharing of final research data. A data sharing plan is required for certain grant applications, including those requesting $500,000 or more in direct costs in any year.</p>
	            <p>
                    <div class="col-md-1 col-md-offset-1"><a href="http://grants.nih.gov/grants/policy/nihgps_2010/nihgps_ch8.htm#_Toc271264951">Policy</a></div>
                    <div class="col-md-1 col-md-offset-1"><a href="http://grants.nih.gov/grants/policy/data_sharing/data_sharing_guidance.htm">Guidance</a></div>
                    <div class="col-md-1 col-md-offset-1"><a href="dmp_examples.php#nih">Examples</a></div>
                    <div class="col-md-1 col-md-offset-1"><a href="http://nexus.od.nih.gov/all/?s=research+data+sharing&submit=Search">News</a></div>
                </p>
                <br />
                <p>**Starting in 2015, all NIH-funded research that generates large-scale human or non-human genomic data must include a genomic data sharing plan in the grant application, and resulting data must be deposited in an NIH-designated data repository.**</p>
                <p>
                    <div class="col-md-1 col-md-offset-1"><a href="http://gds.nih.gov/03policy2.html">Policy</a></div>
                    <div class="col-md-1 col-md-offset-1"><a href="http://gds.nih.gov/pdf/gwas_data_sharing_plan.pdf">Guidance</a></div>
                    <div class="col-md-3 col-md-offset-1"><a href="http://gds.nih.gov/02dr2.html">NIH-designated data repositories<a/></div></a>
                </p>
            <hr>
            <h2>National Science Foundation</h2>
                <p>NSF expects investigators to share primary data generated by NSF-funded research. All grant applications must include a data management plan.</p>
                <p>
                    <div class="col-md-1 col-md-offset-1"><a href="http://www.nsf.gov/pubs/policydocs/pappguide/nsf13001/aag_6.jsp#VID4">Policy</a></div>
                    <div class="col-md-1 col-md-offset-1"><a href="https://www.nsf.gov/bfa/dias/policy/dmp.jsp">Guidance</a></div>
                    <div class="col-md-1 col-md-offset-1"><a href="dmp_examples.php#nsf">Examples</a></div>
                </p>
            <hr>
            <h2>Department of Education</h2>
                <p>The ED’s Institute of Education Sciences expects that research data will be shared with others. A data sharing plan is required for certain grant applications.</p>
                <p>
                    <div class="col-md-1 col-md-offset-1"><a href="http://ies.ed.gov/funding/datasharing_implementation.asp">Policy</a></div>
                    <div class="col-md-1 col-md-offset-1"><a href="http://ies.ed.gov/funding/datasharing_implementation.asp">Guidance</a></div>
                </p>
            <hr>
            <h2>Department of Energy</h2>
                <p>The DOE’s Office of Science states that to the greatest extent possible, research data should be made available to others. All Office of Science grant applications must include a data management plan.</p>
                <p>
                    <div class="col-md-1 col-md-offset-1"><a href="http://science.energy.gov/funding-opportunities/digital-data-management/">Policy</a></div>
                    <div class="col-md-1 col-md-offset-1"><a href="http://science.energy.gov/funding-opportunities/digital-data-management/#Requirements">Guidance</a></div>
                </p>
            <hr>
            <h2>American Heart Association</h2>
                <p>The AHA requires that all grant applications include a data sharing plan and that the resulting data be deposited in an AHA-approved data repository.</p>
                <p>
                    <div class="col-md-1 col-md-offset-1"><a href="http://my.americanheart.org/professional/Research/FundingOpportunities/Open-Science-Policy-Statements-for-AHA-Funded-Research_UCM_461225_Article.jsp">Policy</a></div>
                    <div class="col-md-1 col-md-offset-1"><a href="http://my.americanheart.org/professional/Research/FundingOpportunities/Open-Science-Frequently-Asked-Questions_UCM_461188_Article.jsp#SubmitDataSharingPlan">Guidance</a></div>
                    <div class="col-md-3 col-md-offset-1"><a href="http://my.americanheart.org/professional/Research/FundingOpportunities/AHA-Approved-Data-Repositories_UCM_461443_Article.jsp">AHA-approved data repositories</a></div>
                </p>
            <hr>
            <h2>Department of Health and Human Services</h2>
                <p>The HHS’s Agency for Healthcare Research and Quality indicates that grant applications should specify a plan for sharing research data.</p>
                <p>
                       <div class="col-md-1 col-md-offset-1"><a href="http://grants.nih.gov/grants/guide/pa-files/PA-13-045.html">Policy</a></div>
                </p>
            <hr>
            <h2>National Aeronautics and Space Administration</h2>
                <p>NASA promotes the full and open sharing of all data. All grant applications must include a data management plan.</p>
                <p>
                    <div class="col-md-1 col-md-offset-1"><a href="http://science.nasa.gov/earth-science/earth-science-data/data-information-policy/">Policy</a></div>
                    <div class="col-md-1 col-md-offset-1"><a href="http://science.nasa.gov/earth-science/earth-science-data/data-management-plan-guidance/">Guidance</a></div>
                </p>
            <hr>
            <h2>US Geological Survey</h2>
                <p>The USGS expects that researchers will carefully manage and share their data and encourage the formulation of a data management plan. Some USGS programs require a data management plan as a component of grant applications and provide program-specific guidance (see below).</p>
                <p>
                    <div class="col-md-1 col-md-offset-1"><a href="http://www.usgs.gov/datamanagement/why.php">Policy</a></div>
                    <div class="col-md-1 col-md-offset-1"><a href="http://www.usgs.gov/datamanagement/plan.php">Guidance</a></div>
                    <div class="col-md-1 col-md-offset-1"><a href="dmp_examples.php#usgs">Examples</a></div>
                </p>
                <br/>
                <h5>National Climate Change and Wildlife Center and the Climate Science Centers</h5>
                    <p>
                    <div class="col-md-1 col-md-offset-1"><a href="https://nccwsc.usgs.gov/content/data-policies-and-guidance">Policy</a></div>
                    <div class="col-md-1 col-md-offset-1"><a href="https://nccwsc.usgs.gov/sites/default/files/images/DMPGuidance_v3_0.pdf">Guidance</a></div>
                    </p>
                <br/>
                <h5>Powell Center for Analysis and Synthesis</h5>
                    <p>
                    <div class="col-md-1 col-md-offset-1"><a href="https://powellcenter.usgs.gov/data-management-and-reporting-requirements">Policy</a></div>
                    </p>
                <br/>
                <h5>Alaska Science Center</h5>
                    <p>
                    <div class="col-md-1 col-md-offset-1"><a href="http://www.usgs.gov/datamanagement/documents/ASC-RDMP-Guidance-v1.0.pdf">Policy</a></div>
                    <div class="col-md-1 col-md-offset-1"><a href="http://www.usgs.gov/datamanagement/documents/ASC-RDMP-Example-Wildcast.pdf">Guidance</a></div> 
                    </p>
            <hr>
            <h2>Centers for Disease Control and Prevention</h2>
                <p>The CDC encourages the release and sharing of data as broadly as possible.</p>
                <p>
                    <div class="col-md-1 col-md-offset-1"><a href="http://www.cdc.gov/maso/policy/releasingdata.pdf">Policy</a></div>
                </p>
            <hr>
          </div> <!-- /service -->
        </div> <!-- /col-12 -->
    </div> <!-- /row -->
</div> <!-- /container -->







<?php include('bottom.php'); ?>